baseURL = "https://kelvinmaina.me/"
languageCode = "en-us"
publishDir = "docs"
theme = "aafu"
[build]
  writeStats = true

[params]
    title = "KELVIN MAINA WANGARI"
    author = "Kelvin Maina"
    description = "Website title"
    copyright = "short copyright message"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "ocean"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Kelvin Maina .W."
        tagline = "Computer Scientist"
        location = "City Name: Nairobi"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/kelvin-maina-522877a4/"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-stack-overflow"
            url = "https://stackoverflow.com/users/12234952/kelvin-maina?tab=profile"
            title = "StackOverflow"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/KelvinMW"
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/MKelvinW"
            title = "Twitter"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "As a seasoned computer science and IT consultant, I bring a wealth of experience in crafting innovative solutions for web and mobile development. My proven track record is marked by the successful delivery of high-quality solutions tailored to meet the unique needs of my clients. Notably, I have a published app on the Google Play Store and have developed several impactful web-based solutions, showcasing my ability to transform ideas into reality.My passion for technology extends beyond consultingâ€”I am a dedicated educator in the field of IT. Guided by a teaching philosophy centered around hands-on, project-based learning, I am committed to fostering an inclusive and engaging classroom environment. This approach cultivates creativity, critical thinking, and collaboration among my students. Through my teaching endeavors, I aim to empower the next generation of computer scientists, instilling in them the skills and mindset needed to make meaningful contributions to society. Always eager to embrace the latest industry trends and technologies, I am a fast learner with a commitment to staying at the forefront of advancements. This dual focus on consulting and education reflects my dedication to driving innovation and excellence in the dynamic landscape of computer science"
    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Job Title"
            dates = "2019 - *Present*"
            company = "Company Name"
            details = "Printed from desktop. Sent [emails](#). Called people using telephone. Drank water from office cooler. Ate donuts on people's birthdays."
        [[params.experience.list]]
            position = "Job Title"
            dates = "2018 - 2019"
            url = "#"
            company = "Company Name"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Ph.D. in Subject"
            college = "University of State-City"
            dates = "2013 - 2018"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_url = "#"
        [[params.education.list]]
            degree = "M.S. in Subject"
            college = "University of State-City"
            dates = "2013 - 2018"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_url = "#"
        [[params.education.list]]
            degree = "B.S. in Subject"
            college = "University of State-City"
            dates = "2004 - 2009"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Project 1"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 2"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 3"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 4"
            url = "#"
            description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Cooking"
        [[params.hobby.list]]
            hobby = "Hiking"
        [[params.hobby.list]]
            hobby = "Baking"